### ISSUE TITLE
does callback verify that merchantorderid belongs to the logged in user?

### ISSUE THREAD

**Issue by danmarsden** [duitkupg/moodle-paygw_duitku#25]
Looking at your code - I suspect if I get a valid merchantorder id, I can pass the same details to the callback page while logged in as a different user - allowing me to pay once and get a valid merchantorderid, then log in with as many other users as I want and hit the same page, allowing the users to gain access to the course without having to pay?

**Comment by maikdi** [comment]
I don't think that would be possible for these reason:
1. Should someone try to 'bypass' the callback, they would need to provide all 10 required parameters (which is highly unlikely)
2. Two of those required parameter should only be known by the payment account owner/site admin who holds database access.
3. The callback will also verify the 'signature' parameter with a API Key (again, only known by the payment account owner or those with database access). 

Actually I would like to add 
`if (!empty($_GET))`  as a security measure. But since direct $_GET access is not allowed and for the reasons above, I don't think that would be necessary?

**Comment by danmarsden** [comment]
But isn't all that info exposed to someone when they make the first payment? Just monitoring traffic in their browser then copying the payload and running it again while logged in as someone else?

**Comment by danmarsden** [comment]
Eg the signature doesn't include the userid so would be the same even if another user is logged in.

**Comment by KangLeian** [comment]
The callback information wouldn't be exposed actually, because the callback would be sent from the server. So, if the customer tries to see it by monitoring traffic in their browser it shouldn't be found. We include the order id on the signature as well. So, every signature wouldn't same as the first signature.

We actually haven't checked this, about this issue could you help us by directing us on how to check it? or how the traffic can be copied by the customer?

**Comment by maikdi** [comment]
Adding

> The callback information wouldn't be exposed actually, because the callback would be sent from the server. So, if the customer tries to see it by monitoring traffic in their browser it shouldn't be found. We include the order id on the signature as well. So, every signature wouldn't same as the first signature.
> 
> We actually haven't checked this, about this issue could you help us by directing us on how to check it? or how the traffic can be copied by the customer?

Adding to this. Even if someone is listening on the school network, as long as it's a secure connection, shouldn't the data be encrypted?

**Comment by danmarsden** [comment]
I missed that it was a server level callback rather than in the browsers session, so that does make it slightly better but i think it would still be good to store the userid against the merchant order and check it matches just in case.

So - not a blocker for approval but something worth addressing at some point

**Comment by maikdi** [comment]
Alright. Thanks :D

On the other note. The component, payment area, and user id is also sent in along with the 'additionalParams' parameter which would differ the order delivery anyways.
